### ISSUE TITLE
getting argument error

### ISSUE THREAD

**Issue by akshaygoyal88** [TomasAchmedovas/paysera#6]
Parameters: {"accept"=>nil, "data"=>"YW1vdW50PTEwMDAmY291bnRyeT1MVCZjdXJyZW5jeT1FVVImb3JkZXJpZD0xJnByb2plY3RpZD03MTM4MSZ0ZXN0PTEmdmVyc2lvbj0xLjYmbGFuZz1lbmcmcGF5bWVudD13YWxsZXQmcGF5dGV4dD1PcmRlcitObyUzQSsxK2F0K2h0dHAlM0ElMkYlMkYwLjAuMC4wK3Byb2plY3QuKyUyOFNlbGxlciUzQStBbmRyaXMrJUM0JThDZWtzdGVycyUyOSZwX2VtYWlsPWFrc2hheXl1dmFzb2Z0MTI5JTQwZ21haWwuY29tJnN0YXR1cz0xJnJlcXVlc3RpZD04MzU5Nzc4MCZwYXlhbW91bnQ9MTAwMCZwYXljdXJyZW5jeT1FVVI=", "ss1"=>"bd4c502ba67e23caea0119e81e84aac1", "ss2"=>"qjRhI1EIRQLciQMBuGMFZKEuvvgO6ESOv_CeK1ejughqSVx78KkSAom1UTW0JVgy9_aI3Nq7yBg4vo5zRbeHg7TD7VrwwaKsJr3zCN88CcCDw6GT8BFyiMD0AxSxANV5jNaDPdv0hl2cD_x1PPqmwgTFH1bgXt2SHUu1ARji95I="}

I am unable to get response getting below error
ArgumentError Exception: wrong number of arguments (3 for 1)
on
response =Paysera::Response.new( params, ***\* ,  '**********************')

When i tried with 
Paysera::Response.new( params)
I am getting error
**\* Paysera::Error::Response Exception: Unable to verify 'ss1'
I noticed that
PAYSERA_PUBLIC_KEY = 'http://downloads.paysera.com/download/public.key' is absent

**Comment by minvs1** [comment]
Hello, yes public key url was out-dated. Fixed with 2b855571324d20f656407a5d0d75580d037132ee. Updated and released new gem version. Please update.
