### ISSUE TITLE
Does this validate response domain?

### ISSUE THREAD

**Issue by IvRRimum** [TomasAchmedovas/paysera#7]
I dig trought your code and it looks like it doesnt validate domain from which the response are reaceaved(callbackUrl).

So in theory, anybody could make a request by themselves and accept/complete the payment, without even paying?

**Comment by minvs1** [comment]
It doesn't validate domain name, but it validates SS1 and SS2 signatures. You can read more about them here: https://developers.paysera.com/en/payments/current#macro-callback-structure
